repos:
  - repo: local
    hooks:
      - id: go-test
        name: Go test
        entry: go test ./...
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        entry: hadolint/hadolint:latest-alpine hadolint
        types: ["dockerfile", "file", "non-executable", "text"]


  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint-docker
        types: ["file", "non-executable", "text", "yaml"]
        files: ^.github/workflows