repos:
  - repo: local
    hooks:
      - id: go-test
        name: Go test
        entry: go test ./...
        language: system
        pass_filenames: false

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        types: ["dockerfile", "file", "non-executable", "text"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        language: golang
        types: ["file", "non-executable", "text", "yaml"]
        files: ^.github/workflows