name: stack-api-user-service

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "3000:3000"
      - "9090:9090"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://admin:yes@db:5432/admin
    depends_on:
      - db

  db:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yes
      POSTGRES_USER: admin
      POSTGRES_DB: admin