// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: internal/module/user/grpc/user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запит перевірки по ID
type ExistsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByIDRequest) Reset() {
	*x = ExistsByIDRequest{}
	mi := &file_internal_module_user_grpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByIDRequest) ProtoMessage() {}

func (x *ExistsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_module_user_grpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByIDRequest.ProtoReflect.Descriptor instead.
func (*ExistsByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_module_user_grpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *ExistsByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Відповідь на перевірку по ID
type ExistsByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByIDResponse) Reset() {
	*x = ExistsByIDResponse{}
	mi := &file_internal_module_user_grpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByIDResponse) ProtoMessage() {}

func (x *ExistsByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_module_user_grpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByIDResponse.ProtoReflect.Descriptor instead.
func (*ExistsByIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_module_user_grpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *ExistsByIDResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_internal_module_user_grpc_user_proto protoreflect.FileDescriptor

const file_internal_module_user_grpc_user_proto_rawDesc = "" +
	"\n" +
	"$internal/module/user/grpc/user.proto\x12\x04user\",\n" +
	"\x11ExistsByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x12ExistsByIDResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2N\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"ExistsByID\x12\x17.user.ExistsByIDRequest\x1a\x18.user.ExistsByIDResponseB,Z*api-user-service/internal/module/user/grpcb\x06proto3"

var (
	file_internal_module_user_grpc_user_proto_rawDescOnce sync.Once
	file_internal_module_user_grpc_user_proto_rawDescData []byte
)

func file_internal_module_user_grpc_user_proto_rawDescGZIP() []byte {
	file_internal_module_user_grpc_user_proto_rawDescOnce.Do(func() {
		file_internal_module_user_grpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_module_user_grpc_user_proto_rawDesc), len(file_internal_module_user_grpc_user_proto_rawDesc)))
	})
	return file_internal_module_user_grpc_user_proto_rawDescData
}

var file_internal_module_user_grpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_module_user_grpc_user_proto_goTypes = []any{
	(*ExistsByIDRequest)(nil),  // 0: user.ExistsByIDRequest
	(*ExistsByIDResponse)(nil), // 1: user.ExistsByIDResponse
}
var file_internal_module_user_grpc_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.ExistsByID:input_type -> user.ExistsByIDRequest
	1, // 1: user.UserService.ExistsByID:output_type -> user.ExistsByIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_module_user_grpc_user_proto_init() }
func file_internal_module_user_grpc_user_proto_init() {
	if File_internal_module_user_grpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_module_user_grpc_user_proto_rawDesc), len(file_internal_module_user_grpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_module_user_grpc_user_proto_goTypes,
		DependencyIndexes: file_internal_module_user_grpc_user_proto_depIdxs,
		MessageInfos:      file_internal_module_user_grpc_user_proto_msgTypes,
	}.Build()
	File_internal_module_user_grpc_user_proto = out.File
	file_internal_module_user_grpc_user_proto_goTypes = nil
	file_internal_module_user_grpc_user_proto_depIdxs = nil
}
