name: Build
on:
  push:
    branches:
      - develop
  workflow_dispatch:


permissions:
  contents: read # This is required for actions/checkout
  packages: write # This is required for save docker images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true


jobs:
  vars:
    name: Generation vars
    runs-on: ${{ vars.RUNS_OS }}
    steps:
      # Logic
      - name: Set prefix
        run: echo 1

  test-dockerfile:
    needs: [ vars ]
    uses: open-bill-stack/github-workflows/.github/workflows/dockerfile-test.yaml@develop
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_call.workflow_file }}-test-dockerfile
      cancel-in-progress: true
    with:
      RUNS_ON: ${{ vars.RUNS_OS }}
      HADOLINT_CHECK_ENABLE: true

  test-go:
    needs: [ vars ]
    uses: open-bill-stack/github-workflows/.github/workflows/go-test.yaml@develop
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_call.workflow_file }}-test-golang
      cancel-in-progress: true
    with:
      RUNS_ON: ${{ vars.RUNS_OS }}
      GO_VERSION: "1.24"

  build:
    needs: [ vars, test-dockerfile, test-go ]
    name: Build
    runs-on: ${{ vars.RUNS_OS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        id: login-repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create meta tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,priority=1000,prefix=sha-,suffix=-app
            type=raw,value=latest,priority=0,suffix=-app,enable={{is_default_branch}}
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 12

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          provenance: false
          target: prod
          tags: |
            ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
